---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---


```{block type='savequote', quote_author='(ref:osler-quote)', include=knitr::is_latex_output()}
Medicine is a science of uncertainty and an art of probability.
```
(ref:osler-quote) --- *Sir William Osler* (1849--1919).

<!-- 
Notes for adding an opening quote in PDF output:
i) add the reference for the quote with the chunk option quote_author="my author name",
ii) include=knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex' means that these quotes are only included when output is latex (in HTML output, it would appear by the end of the previous page)
iii) You can't use markdown syntax inside chunk options, so if you want to e.g. italicise a book name in the quote reference use a 'text reference': Create a named piece of text with '(ref:label-name) My text', then link to this in the chunk option with quote_author='(ref:label-name)'
-->

# Introduction

Fluid therapy is a ubiquitous medical intervention; both in the perioperative setting and for hospitalised patients in general. The aim of fluid therapy is to restore the patient’s circulating blood volume to the *optimum*, normal, level. Hence, the terms “fluid *resuscitation*” and “fluid *replacement* therapy” are commonly used. 

Intraoperative fluid management is mainly relevant in acute or long-duration surgery. 
In acute surgery, the preoperative fluid status is generally unknown, and it is often reasonable to assume that the patient arrives at the operating room dehydrated. 
In long-duration surgery, continuous loss of fluid through bleeding, perspiration and urination necessitates fluid replacement through the operation. Since these patients are anaesthetised, intravenous (IV) is the administration route of choice.

Like every treatment, IV fluid should only be given to patients who will benefit from the fluid. 
This is the setup for a prediction problem: can we, ahead of time, predict whether a patient will benefit from an intravenous fluid administration? 
The first task is to define what we mean with *benefit*, and how we can measure it. This is not trivial, and it will be discussed further in section ??. 
Luckily, a necessary (but not sufficient) condition for benefitting from a fluid administration is that the fluid causes an increase in cardiac output (CO). 
This can be measured, and allows us to formulate a simpler prediction problem: 

Can we predict whether a patient’s CO will increase from a fluid administration? 

There is an entire subfield of anaesthesia and intensive care research dealing with this problem.
This PhD dissertation describes a small, but hopefully meaningful addition to the field.

In this dissertation I present the available tools for fluid responsiveness prediction in the intraoperative setting. The dissertation describes 3 papers that tackle specific limitations to the currently available tools.  

The terms fluid challenge and bolus are used interchangeably. Stroke volume (SV) and cardiac output (CO) are often interchangeable and the term that best fits the context is used.
